#!/bin/sh
_gittopdir () {
   if [ -d .git ]; then
       pwd
   elif [ `pwd` = / ]; then
       echo "You are not in a git directory." >&2
       return 1
   else
       cd ..
       _gittopdir
   fi
}

_gittopdir="$(_gittopdir)" || pwd
echo $_gittopdir
